Tsarev/hw 9
TsDmitriy/niffler-st5 pull request #6
Opened 2024-05-28 10:49 UTC by TsDmitriy

1. Реализован поиск Category / AuthUser / User по полям category (текстовое название категории), username пользователя.
2. Переведены Extension-ы для создания пользователя и Spend / Category на использование RepositoryHibernate
3. Написал пару  условных тестов на проверку работы методов

2024-06-01 05:42 UTC, sashkir7 requested changes
Доброе утро! С первым днем лета!

По работе необходим ряд правок:
1. Дописать реализации методов по работе с БД.
2. Важный момент: "Перевести свои Extension-ы для создания пользователя и Spend / Category на использование RepositoryHibernate". 
Важно понимать, что экземпляр Repository для работы с БД, созданный в extension, как свойство класса - будет существовать в ед. экземпляре НА ВСЕ ПОТОКИ тестов. Это связано с тем, что Junit создает ед. экземпляр extension-класса. Таким образом, при параллельном прогоне тестов могут наблюдаться проблемы

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/SpendRepositoryJdbc.java
> +    }
Хорошо бы через голый jdbc тоже реализовать

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/CategoryEntity.java
> +@Getter
Пустая строка после импортом и перед геттером

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/UserEntity.java
> +        }
А если попробовать не через итератор, а через, например, friendshipRequests.removeIf()

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepository.java
> +        return new SpendRepositoryHybernate();
Hibernate - через i

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepository.java
> +    CategoryEntity findCategory(String category);
Искать категорию нужно по наименованию категории и имени пользователя
Если мы ищем категорию только по наименованию категории, то на выходе должен быть список найденных категорий, тк одно и тоже наименовании категории может быть у нескольких пользователей

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHybernate.java
> +    }
Можно записать "в одну строку"
```
    public CategoryEntity findCategory(String category) {
        String hql = "FROM CategoryEntity WHERE category = :category";
        return em.createQuery(hql, CategoryEntity.class)
                .setParameter("category", category)
                .getSingleResult();
    }
```

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHybernate.java
> +    }
А здесь почему нет реализации?

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryHybernate.java
> +    }
И здесь тоже?

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositoryJdbc.java
> +    }
И тут

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/SpendRepositorySpringJdbc.java
> +    }
И здесь

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepository.java
> +        if("sjdbc".equals(System.getProperty("repo"))){
Мы же выше написали final String repo = System.getProperty("repo");
Для чего еще раз sys property получать?

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositoryJdbc.java
> +    }
Реализация

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositoryJdbc.java
> +    }
Здесь тоже

2024-06-01 05:42 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositorySpringJdbc.java
> +    }
И тут

2024-06-04 12:53 UTC, TsDmitriy commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/CategoryEntity.java
> +@Getter
фикс

2024-06-04 12:55 UTC, TsDmitriy commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/repository/UserRepositorySpringJdbc.java
> +    }
Доработано

2024-06-06 07:01 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/data/entity/UserEntity.java
> +        }
В таком случае - окей. 
Вариант, когда мы из разработческого кода заимствуем некоторые его части (например, entity и dto классы) - это вполне нормально. Не надо изобретать велосипед =)

2024-06-06 07:03 UTC, sashkir7 approved these changes
Очень хорошо!

2024-06-06 07:06 UTC, merged